### ISSUE TITLE
Acceptance Test #7 | US27: As a user, I would like to navigate from my desired start point / current location to my desired destination.

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#178]
### Story
As a user, I would like to navigate from my desired start point / current location to my desired destination.

### Steps to reproduce
1. Start the application
2. Tap on a search bar & query a building of choice
3. Click on _Get Directions_ in the bottom menu
4. Click on Starting Position & put _Current Position_
5. Wait a few seconds as the app is fetching your location
6. Click on View Route

**Note: you can also access the search page by using the search bar in the map**

### Preview
![us21](https://user-images.githubusercontent.com/34899555/77562549-885a7200-6e96-11ea-964e-e0e3fd3de2c1.gif)

**Comment by jodavimehran** [comment]
Please select the current location as a default for the From and also fix the problem that mentioned in step five (remove the step five).

**Comment by AlainJobs** [comment]
Hi Sir, yeah step 5 was fixed and will be removed. However, we asserted that setting the CurrentPosition as default is harder than expected, thus, until it's done, the user has to select CurrentLocation in the dropdown menu.

See PR #171 for detailed info.
Briefly, the complication occurs when the user tries to select another starting position (not current location) and then revert back to wanting the currentLocation, we have no way to catch an empty selection. That's also why we added CurrentLocation as an element (for now).

**Comment by AlainJobs** [comment]
Wait, were you referring to the waiting time in Step **5** or the fix for step **4**?

**Comment by jodavimehran** [comment]
> Wait, were you referring to the waiting time in Step **5** or the fix for step **4**?


"5. Click on the second search bar & enter building of choice (will be fixed)"
this is redundant because the user selected it in step 3.

**Comment by AlainJobs** [comment]
Step 5 was removed, and also we had duplicated step 3. 
Also, were you able to run the app properly? And if you acknowledged my first reply, we wanted to know if this acceptance test passed or not for you. Besides your remark for which we will work on, the goal is reached. Thank you

**Comment by jodavimehran** [comment]
> Also, were you able to run the app properly? And if you acknowledged my first reply, we wanted to know if this acceptance test passed or not for you. Besides your remark for which we will work on, the goal is reached. Thank you

I built and run the latest version of the app from the master branch.
I select a building and click on Get Directions. It navigates me to another page where I can select my current location as a starting position. But it shows me the attached message. So I think in this scenario the problem didn't solve. 

![image](https://user-images.githubusercontent.com/55111960/77979967-1938af80-72d4-11ea-976a-d1c372864743.png)

**Comment by AlainJobs** [comment]
Sir, it does work. You just have to wait max 5 seconds for the currentlocation to be fetched like explained in _step 5_. We have to add a loading or update the _alert message_ to at least give the user more feedback.

**Comment by AlainJobs** [comment]
Actually, you found a bug, I just tested it out, and it seems like LB Building coordinates are not found, while all the other buildings work.

**Comment by AlainJobs** [comment]
Actually, you found a bug, I just tested it out, and it seems like LB Building coordinates are not found, while all the other buildings work. I will report this bug and how to fix it. But again, it only concerns that specific building. We didn't catch it because it works for the rest of the buildings except for the buildings with the same issue as LB Building (EV Building, JMSB, GM Building). It's a quick fix, will this acceptance would be considered passed if we fix it right now?

**Comment by AlainJobs** [comment]
> Actually, you found a bug, I just tested it out, and it seems like LB Building coordinates are not found, while all the other buildings work. I will report this bug and how to fix it. But again, it only concerns that specific building. We didn't catch it because it works for the rest of the buildings except for the buildings with the same issue as LB Building (EV Building, JMSB, GM Building). It's a quick fix, will this acceptance would be considered passed if we fix it right now?

Following the above reply, this was fixed. Also, we were wondering what does it mean when you don't give an answer to an acceptance test. In some, you added accepted, and some others nothing...  We are concerned since on our end, everything work, thus, having at least some feedback could be useful! Thank you very much.

**Comment by jodavimehran** [comment]
> > Actually, you found a bug, I just tested it out, and it seems like LB Building coordinates are not found, while all the other buildings work. I will report this bug and how to fix it. But again, it only concerns that specific building. We didn't catch it because it works for the rest of the buildings except for the buildings with the same issue as LB Building (EV Building, JMSB, GM Building). It's a quick fix, will this acceptance would be considered passed if we fix it right now?
> 
> Following the above reply, this was fixed. Also, we were wondering what does it mean when you don't give an answer to an acceptance test. In some, you added accepted, and some others nothing... We are concerned since on our end, everything work, thus, having at least some feedback could be useful! Thank you very much.

I will check the other tests without comment and this one tonight by building the latest version of your app. So if some tests are accepted you can close it.
